- id: '1609602252443'
  alias: Turn off living room lights
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    to: not_home
  - platform: state
    entity_id: group.phone
    to: 'off'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.family
      state: not_home
    - condition: state
      entity_id: group.phone
      state: 'off'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.tv_light
  mode: single
- id: '1610029670345'
  alias: Tag Living Room is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 7131afcc-6b80-45f5-808d-e9daf866266b
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.game_mode_on_off
  mode: single
- id: '1610372640571'
  alias: Tag Bedroom is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 3db49055-630b-432e-8fae-077b54e13632
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.bedroom
  mode: single
- id: '1610374154686'
  alias: Tag Study is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 48fd88bf-1742-4770-9c9b-c0801da14c15
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.bedroom
  mode: single
- id: '1613457110972'
  alias: Turn off bedroom light
  description: ''
  trigger:
  - platform: state
    from: discharging
    to: charging
    entity_id: sensor.nokia_battery_state
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.bedroom
  mode: single
- id: '1613457968409'
  alias: Turn on living room lights
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    to: home
  - platform: state
    entity_id: group.phone
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: group.phone
      state: 'on'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.tv_light
  mode: single
