- id: '1613966165791'
  alias: Tag Office is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: a4f8caa1-955c-4c8c-a192-6691badedeba
  condition: []
  action:
  - service: notify.mobile_app_pixel_6
    data:
      message: I'm coming home
  - service: tts.google_say
    data:
      message: I'm coming home
      entity_id: media_player.hub
  mode: single
- id: '1610029670345'
  alias: Tag Living Room is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 7131afcc-6b80-45f5-808d-e9daf866266b
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.game_mode_on_off
  mode: single
- id: '1610372640571'
  alias: Tag Bedroom is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 3db49055-630b-432e-8fae-077b54e13632
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.bedroom_light
  mode: single
- id: '1610374154686'
  alias: Tag Study is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 48fd88bf-1742-4770-9c9b-c0801da14c15
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.study_light
  mode: single
- id: '1613457110972'
  alias: Turn off bedroom light
  description: ''
  trigger:
  - platform: state
    to: charging
    entity_id: sensor.oneplus_battery_state
  condition:
  - condition: state
    entity_id: person.omar
    state: home
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.bedroom_light
  mode: single
- id: '1613457968409'
  alias: Turn on camera snapshot
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.camera_motion
    to: 'on'
  condition: []
  action:
  - service: camera.snapshot
    target:
      entity_id: camera.camera_hd
    data:
      filename: /media/temp/{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg
  - service: notify.mobile_app_le2100
    data:
      message: Someone is here!
  mode: single
- id: '1613912863622'
  alias: Turn on alarm trigger
  description: ''
  trigger:
  - platform: state
    to: 'on'
    entity_id: group.sensor
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarm_system
    state: armed_away
  action:
  - service: notify.notify
    data:
      message: Motion detected/door opened someone at home!
  - service: media_player.play_media
    data:
      media_content_type: music
      media_content_id: media-source://media_source/local/Alarm.mp3
    target:
      entity_id:
      - media_player.nest
      - media_player.lenovo
      - media_player.hub
      - media_player.home
  - service: camera.record
    data:
      filename: /media/movement_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4
    target:
      entity_id: camera.camera_hd
  mode: single
- id: '1613913011922'
  alias: Turn off alarm trigger
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.camera_motion
    to: 'off'
  - platform: state
    entity_id: binary_sensor.kitchen_door
    to: 'off'
  condition: []
  action:
  - service: media_player.turn_off
    target:
      entity_id:
      - media_player.nest
      - media_player.lenovo
      - media_player.hub
      - media_player.home
    data: {}
  mode: single
- id: '1613916020645'
  alias: Turn on alarm system
  description: ''
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm_system
    to: armed_away
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.camera_on_off
  - service: switch.turn_on
    data: {}
    entity_id: switch.alarm_on_off
  - service: notify.notify
    data:
      message: Alarm system is online!
  mode: single
- id: '1613916123236'
  alias: Turn off alarm system
  description: ''
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm_system
    to: disarmed
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.camera_on_off
  - service: switch.turn_off
    data: {}
    entity_id: switch.alarm_on_off
  - service: notify.notify
    data:
      message: Alarm system is offline!
  mode: single
- id: '1613919064454'
  alias: Turn on bedroom light
  description: ''
  trigger:
  - platform: time
    at: '23:59'
  condition:
  - condition: state
    entity_id: person.omar
    state: home
  - condition: and
    conditions:
    - condition: state
      entity_id: sensor.oneplus_battery_state
      state: discharging
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.bedroom_light
  mode: single
- id: '1626957363206'
  alias: Turn off the home mode
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    to: not_home
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - platform: state
    entity_id: group.phone
    to: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: group.family
      state: not_home
    - condition: state
      entity_id: group.phone
      state: 'off'
  action:
  - service: tapo_control.set_privacy_mode
    data:
      privacy_mode: 'off'
    target:
      entity_id: camera.camera_hd
  - service: media_player.turn_off
    target:
      entity_id:
      - media_player.panasonic
      - media_player.youtube
      - media_player.hub
    data: {}
  - service: switch.turn_off
    target:
      entity_id:
      - switch.living_light
      - switch.movie_light
      - switch.kitchen_light
    data: {}
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.bedroom_light
      - light.study_light
  mode: single
- id: '1626957484012'
  alias: Turn on the home mode
  description: ''
  trigger:
  - platform: state
    to: home
    entity_id: group.family
  condition: []
  action:
  - service: tapo_control.set_privacy_mode
    data:
      privacy_mode: 'on'
    target:
      entity_id: camera.camera_hd
  - service: switch.turn_on
    target:
      entity_id:
      - switch.living_light
    data: {}
  mode: single
- id: '1637479980521'
  alias: Accidental trigger notification
  description: ''
  trigger:
  - platform: state
    entity_id: group.light
    to: 'on'
  condition:
  - condition: state
    entity_id: group.family
    state: not_home
    for:
      hours: 0
      minutes: 2
      seconds: 0
  action:
  - service: notify.notify
    data:
      message: Something turn on the light!
  mode: single
- id: '1643908928112'
  alias: Door button press
  description: ''
  trigger:
  - platform: state
    entity_id: input_button.door
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.sonoff_100146cdce
  mode: single
- id: '1648638637289'
  alias: Open the door when family come to home
  description: ''
  trigger:
  - platform: state
    entity_id: person.omar
    to: home
  - platform: state
    entity_id: person.p_m_wu
    to: home
  condition: []
  action:
  - service: button.press
    data: {}
    target:
      entity_id: input_button.door
  mode: single
