- id: '1613966165791'
  alias: Tag Office is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: a4f8caa1-955c-4c8c-a192-6691badedeba
  condition: []
  action:
  - service: notify.mobile_app_htc
    data:
      message: Omar is coming home!
  mode: single
- id: '1610029670345'
  alias: Tag Living Room is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 7131afcc-6b80-45f5-808d-e9daf866266b
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.game_mode_on_off
  mode: single
- id: '1610372640571'
  alias: Tag Bedroom is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 3db49055-630b-432e-8fae-077b54e13632
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.bedroom
  mode: single
- id: '1610374154686'
  alias: Tag Study is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 48fd88bf-1742-4770-9c9b-c0801da14c15
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.bedroom
  mode: single
- id: '1613457110972'
  alias: Turn off bedroom light
  description: ''
  trigger:
  - platform: state
    to: charging
    entity_id: sensor.nokia_battery_state
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.bedroom
  mode: single
- id: '1609602252443'
  alias: Turn off living room light
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    to: not_home
  - platform: state
    entity_id: group.phone
    to: 'off'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.family
      state: not_home
    - condition: state
      entity_id: group.phone
      state: 'off'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.movie_light
  mode: single
- id: '1613457968409'
  alias: Turn on living room light
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.camera_motion
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.movie_light
  mode: single
- id: '1613912863622'
  alias: Turn on alarm trigger
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.camera_motion
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  - condition: and
    conditions:
    - condition: state
      entity_id: group.family
      state: not_home
  action:
  - service: notify.notify
    data:
      message: Motion detected someone at home!
  - service: media_player.media_play
    data:
      entity_id: group.speaker
      media_content_type: music
      media_content_id: media-source://media_source/local/Alarm.mp3
  mode: single
- id: '1613913011922'
  alias: Turn off alarm trigger
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.camera_motion
    to: 'off'
  condition: []
  action:
  - service: media_player.stop
    data:
      entity_id: group.speaker
  mode: single
- id: '1613916020645'
  alias: Turn on alarm system
  description: ''
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: armed_away
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.camera_on_off
  - service: switch.turn_on
    data: {}
    entity_id: switch.alarm_on_off
  - service: notify.notify
    data:
      message: Alarm system is online!
  mode: single
- id: '1613916123236'
  alias: Turn off alarm system
  description: ''
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: disarmed
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.camera_on_off
  - service: switch.turn_off
    data: {}
    entity_id: switch.alarm_on_off
  - service: notify.notify
    data:
      message: Alarm system is offline!
  mode: single
- id: '1613919064454'
  alias: Turn on bedroom light
  description: ''
  trigger:
  - platform: time
    at: '23:59'
  condition:
  - condition: state
    entity_id: person.omar
    state: home
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.bedroom
  mode: single
- id: '1613921281886'
  alias: Change TV mode
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.tv_mode
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.tv_mode
        state: Youtube
      sequence:
      - service: switch.turn_on
        data: {}
        entity_id: switch.tv_youtube
    - conditions:
      - condition: state
        entity_id: input_select.tv_mode
        state: Netflix
      sequence:
      - service: switch.turn_on
        data: {}
        entity_id: switch.tv_nextflix
    - conditions:
      - condition: state
        entity_id: input_select.tv_mode
        state: HDMI
      sequence:
      - service: switch.turn_on
        data: {}
        entity_id: switch.tv_hdmi
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
      - service: switch.turn_off
        data: {}
        entity_id: switch.tv_hdmi
    default: []
  mode: single
- id: '1615043315433'
  alias: Turn on study light
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.door_sensor
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.door_sensor
        state: 'on'
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.movie_light
    - conditions:
      - condition: state
        entity_id: binary_sensor.door_sensor
        state: 'off'
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.movie_light
  mode: single
- id: '1615126056334'
  alias: Turn off study light
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.movie_light
  mode: single
