# Example configuration.yaml entry
default_config:

# Config
discovery:
wake_on_lan:

homeassistant:
  customize: !include customize.yaml

# Camera
camera:
  - platform: ffmpeg
    name: D-Link Tapo C100
    input: !secret camera_input
    
# Google Calendar
google:
  client_id: !secret google_cal_id
  client_secret: !secret google_cal_secret
    
# Include
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
google_assistant: !include google_assistant.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
switch: !include switches.yaml

# Https
http:
  server_port: !secret server_port
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Spotify
spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

# Sensor
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: processor_use
      - type: last_boot
      - type: memory_use_percent
      - type: processor_temperature

# Text to speech
tts:
  platform: google_translate
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300
  service_name: google_say
  language: en-uk
