# Example configuration.yaml entry
default_config:

# Config
discovery:
stream:
wake_on_lan:

homeassistant:
  customize: !include customize.yaml

alarm_control_panel: !include alarm_control_panel.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
google_assistant: !include google_assistant.yaml
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
localtuya: !include localtuya.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml

# Google Calendar
google:
  client_id: !secret google_cal_id
  client_secret: !secret google_cal_secret

# Https
http:
  server_port: !secret server_port
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Rest
rest_command:
  assistant_relay:
    url: !secret rest_url
    method: 'post'
    content_type: 'application/json'
    payload: '{"user": "Omar", "command": "{{ message }}"}'
  # p00c_command:
  #   url: !secret p00c_commands

# Spotify
spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say
