# Example configuration.yaml entry
default_config:

# Config
discovery:
stream:
wake_on_lan:

homeassistant:
  customize: !include customize.yaml
  currency: USD
  external_url: !secret external_url
  internal_url: !secret internal_url
  media_dirs:
    local: /media
    recording: /media/temp

alarm_control_panel: !include alarm_control_panel.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
google_assistant: !include google_assistant.yaml
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
localtuya: !include localtuya.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml

# Device Tracker
# device_tracker:
#   - platform: netgear
#     host: !secret netgear_host
#     username: !secret netgear_name
#     password: !secret netgear_password
#     interval_seconds: 10
#     consider_home: 180
#     new_device_defaults:
#       track_new_devices: true

# Google Calendar
# google:
#   client_id: !secret google_cal_id
#   client_secret: !secret google_cal_secret

# Https
http:
  # server_port: !secret server_port
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.200
    - 172.30.33.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 3

# # Rest
# rest_command:
#   assistant_relay:
#     url: !secret rest_url
#     method: 'post'
#     content_type: 'application/json'
#     payload: '{"user": "Omar", "command": "{{ message }}"}'

# Spotify
spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

# Sonoff
# sonoff: 
#   username: !secret sonoff_id
#   password: !secret sonoff_password
#   mode: local

# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say
