# Example configuration.yaml entry
default_config:

homeassistant:
  customize: !include customize.yaml

# Google Assistant
google_assistant:
  project_id: !secret project_id
  report_state: true
  service_account: !include Google_assistant.json
  exposed_domains:
    - switch
    - light
    - media_player
    - scene
    - climate
    - cover
    - person
    - fan
    - automation
    - remote
    - input_boolean
    - sensor
    - binary_sensor
    - device_tracker
    
# Google Calendar
google:
  client_id: !secret google_cal_id
  client_secret: !secret google_cal_secret
    
# Include
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

# Https
http:
  server_port: !secret server_port
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Spotify
spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

# Sensor
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: processor_use
      - type: last_boot
      - type: memory_use_percent
      - type: processor_temperature
      - type: throughput_network_in
        arg: hassio
      - type: throughput_network_out
        arg: hassio

# Switch
switch:
  - platform: wake_on_lan
    mac: !secret desktop_mac
    
# Text to speech
tts:
  platform: google_translate
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300
  service_name: google_say
  language: en-uk
