# Example configuration.yaml entry
default_config:

# Google Assistant
google_assistant:
  project_id: !secret project_id
  report_state: true
  service_account: !include Google_assistant.json
  exposed_domains:
    - switch
    - light
    - media_player
    - scene
    - climate
    - cover
    - person
    - fan
    - automation
    - remote
    - input_boolean
    - sensor
    - binary_sensor
    - device_tracker
    
# Google Calendar
google:
  client_id: !secret google_cal_id
  client_secret: !secret google_cal_secret
    
# Include
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# https
http:
  server_port: !secret server_port
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Spotify
spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

# Text to speech
tts:
  platform: google_translate
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300
  service_name: google_say
  language: en-uk
  