# System
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: processor_use
    - type: last_boot
    - type: memory_use_percent
    - type: processor_temperature
