- platform: scrape
  name: Price 95
  resource: https://vipmember.tmtd.cpc.com.tw/mbwebs/ShowListPrice.aspx?prodtype=1
  scan_interval: 86000
  select: 'tr:nth-of-type(5) td[align]'
  headers:
    User-Agent: 'Mozilla/5.0'

- platform: scrape
  name: Price kerosene
  resource: https://vipmember.tmtd.cpc.com.tw/mbwebs/ShowListPrice.aspx?prodtype=3
  scan_interval: 86200
  select: 'tr:nth-of-type(2) td[align]'
  headers:
    User-Agent: 'Mozilla/5.0'

- platform: scrape
  name: Price kerosene canned
  resource: https://vipmember.tmtd.cpc.com.tw/mbwebs/ShowListPrice.aspx?prodtype=3
  scan_interval: 86300
  select: 'tr:nth-of-type(5) td[align]'
  headers:
    User-Agent: 'Mozilla/5.0'

- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_temperature
    - type: processor_use
