- platform: broadlink
  mac: !secret living_room_mac
  switches:
    - name: "soundbar power"
      command_on: "JgDMAEsWJhUSFiYVEhYmFRIWEhUTFRIWEhUSFiYVJhYSFRIAAshNFiYVEhYmFRIWJhUSFhIVEhYSFRMVEhYmFSYVExUSAALITRYmFRIWJhUSFiYVEhYTFBIWEhUTFRIWJhUmFRMVEgACyE0WJRYSFiUWEhYlFhIWEhUTFRIVExUSFiUWJhUSFhIAAsdOFSYWEhUmFhIVJhYSFRIWEhUTFRIWEhUmFiYVEhYSAALHThUmFRMVJhUTFSYVExUSFhIVExUSFhIVJhUmFhIVEwANBQAAAAAAAAAAAAA="
      command_off: "JgDMAEsWJhUSFiYVEhYmFRIWEhUTFRIWEhUSFiYVJhYSFRIAAshNFiYVEhYmFRIWJhUSFhIVEhYSFRMVEhYmFSYVExUSAALITRYmFRIWJhUSFiYVEhYTFBIWEhUTFRIWJhUmFRMVEgACyE0WJRYSFiUWEhYlFhIWEhUTFRIVExUSFiUWJhUSFhIAAsdOFSYWEhUmFhIVJhYSFRIWEhUTFRIWEhUmFiYVEhYSAALHThUmFRMVJhUTFSYVExUSFhIVExUSFhIVJhUmFhIVEwANBQAAAAAAAAAAAAA="
    - name: "soundbar mute"
      command_on: "JgDuAEwWEhUSFiYVEhYmFRIWEhUTFRIWEhUSFiYVJhYSFRIAAtxNFhIVEhYmFRIWJhUSFhIVExUSFhIVEhYmFSYWEhUTAALbTRUTFRIWJhUSFiYVEhYSFRIWEhYSFRIWJhUmFRMVEgAC204VEhYSFiUWEhYlFhIWEhUSFhIVExUSFiUWJhUTFRIAAttOFRIWEhUmFhIVJhYSFRMVEhYSFRIWEhUmFiYVEhYSAALbTRYSFRMVJhUTFSYVExUSFhIVEhYSFRMVJhUmFhIVEgAC3E0VExUTFSYVEhYlFhIWEhUSFhIVExUSFiYVJhUTFRIADQUAAAAAAAAAAA=="
      command_off: "JgDuAEwWEhUSFiYVEhYmFRIWEhUTFRIWEhUSFiYVJhYSFRIAAtxNFhIVEhYmFRIWJhUSFhIVExUSFhIVEhYmFSYWEhUTAALbTRUTFRIWJhUSFiYVEhYSFRIWEhYSFRIWJhUmFRMVEgAC204VEhYSFiUWEhYlFhIWEhUSFhIVExUSFiUWJhUTFRIAAttOFRIWEhUmFhIVJhYSFRMVEhYSFRIWEhUmFiYVEhYSAALbTRYSFRMVJhUTFSYVExUSFhIVEhYSFRMVJhUmFhIVEgAC3E0VExUTFSYVEhYlFhIWEhUSFhIVExUSFiYVJhUTFRIADQUAAAAAAAAAAA=="
    - name: "soundbar volume"
      command_on: "JgDMAEwVEhUmFhIVExUmFRIWEhUTFRIWEhUSFiYVJhYTFBIAAtxNFRIWJxQSFhMUJhYSFRMVEhYTFBIWEhUmFiYVEhYSAALbTRYSFiUWEhYSFSYWEhUSFhIVExUSFhIVJxUlFhIWEwAC2k0WEhYmFRIVExUmFRIWEhYSFRIWExQTFSYVJhYTFBIAAttOFRMVJhUTFRIWJRYSFhIVEhYSFRMVEhYmFSYVEhYSAALbThUSGSMVEhYSFSYWEhUTFRIVExUTFRIVJxUlFhIWEgANBQAAAAAAAAAAAAA="
      command_off: "JgDMAEwVJhUmFhIVExUmFRMVEhYSFRIWEhUTFScUJhYSFRMAAsdNFiYVJxQTFRIWJhUSFhIVEhYSFRMVEhYmFScUExUSAALHThUmFiYVEhYSFScVEhUSFhIWExQSFhMUJhYmFRIWEgACx04VJhUmFhMUExUmFRMVEhYSFRIWEhUTFSYVJhYTFBMAAsdNFiYVJhUTFRIWJhUSFhIVEhYSFRMVEhYmFSYVExUSAALITRUmFiUWExUSFSYVExUSFhIVEhYSFRMVJhUnFRIVEgANBQAAAAAAAAAAAAA="
    - name: "soundbar display"
      command_on: "JgDMAEsWJhUmFhIVJhYSFRIWJhUSFhIVEhYSFiUWJhUTFRIAArRNFiUWJhUTFSYVExUSFiUWEhYSFRIWExQmFiYVEhYSAAKzThUmFiYVEhYmFRIWExQmFhIVEhYSFRMVJhUmFhIVEwACs04VJhUmFhIVJhYSFRIWJhUTFRIVExUSFiYVJhUTFRIAArRNFiYVJhUTFSYVExUTFSYVExUSFRIWEhUmFiYVEhYSAAK0TRYlFiYVEhYmFRMVEhYlFhIWEhUSFhIVJhYmFRIWEgANBQAAAAAAAAAAAAA="
      command_off: "JgDMAEsWJhUmFhIVJhYSFRIWJhUSFhIVEhYSFiUWJhUTFRIAArRNFiUWJhUTFSYVExUSFiUWEhYSFRIWExQmFiYVEhYSAAKzThUmFiYVEhYmFRIWExQmFhIVEhYSFRMVJhUmFhIVEwACs04VJhUmFhIVJhYSFRIWJhUTFRIVExUSFiYVJhUTFRIAArRNFiYVJhUTFSYVExUTFSYVExUSFRIWEhUmFiYVEhYSAAK0TRYlFiYVEhYmFRMVEhYlFhIWEhUSFhIVJhYmFRIWEgANBQAAAAAAAAAAAAA="
    - name: "soundbar vertical"
      command_on: "JgDcAEwVEhYmFScUJhYmFSYWJhUSFhIVEhYSFSYWEhUTFRMVJhUSFiYVExUSAAGyTRYSFSYWJhUmFiYVJhUmFhIVExUSFhIVJhYSFRIWEhUnFRIVJhYSFRMAAbJNFhIVJhYmFSYVJhYmFSYWExQTFRMUExUnFBMVEhYSFSYWEhUmFhIVEgABs00WEhUmFSYWJhUmFiYVJhUTFRIWEhUSFiYVExUSFRIWJhUSFiYVExUSAAGyThUSFiYVJhYmFSYVJhYnFBIWEhUTFRIWJhUSFhIVEhYmFRIWJhUSFhIADQUAAAAAAAAAAAAA"
      command_off: "JgDcAEwVEhYmFScUJhYmFSYWJhUSFhIVEhYSFSYWEhUTFRMVJhUSFiYVExUSAAGyTRYSFSYWJhUmFiYVJhUmFhIVExUSFhIVJhYSFRIWEhUnFRIVJhYSFRMAAbJNFhIVJhYmFSYVJhYmFSYWExQTFRMUExUnFBMVEhYSFSYWEhUmFhIVEgABs00WEhUmFSYWJhUmFiYVJhUTFRIWEhUSFiYVExUSFRIWJhUSFiYVExUSAAGyThUSFiYVJhYmFSYVJhYnFBIWEhUTFRIWJhUSFhIVEhYmFRIWJhUSFhIADQUAAAAAAAAAAAAA"
    - name: "soundbar desktop"
      command_on: "JgA0AUwVExUSFhIVEhYmFRIWEhUTFRIWEhUSFiYVEhYSFRMVJhUTFSYVExUSAAIVThUSFhIVExUSFiYVFBQSFRIWEhUTFRIWJhUSFhIVExUmFRMVJhUTFRIAAhVOFRIWEhUTFRIWJhUSFhIVEhYSFRMVEhYmFRIWEhUSFiYVEhYmFRIWEgACFU4VEhYSFRMVEhYlFhIWEhUSFhIVExUSFiYVEhYSFRIWJhUSFiYVEhYSAAIVThUSFhIVExUSFiUWEhYSFRIWEhUTFRIWJhUSFhIVEhYmFRIWJhUSFhIAAhVOFRIWEhUSFhIWJRYSFhIVEhYSFRMVEhYlFhIWEhUSFiYVEhYmFRIWEgACFU4VEhYSFRIWEhUmFhIWEhUSFhIVEhYSFiUWEhYSFRIWJhUSFiYVEhYSAA0FAAA="
      command_off: "JgA0AUwVExUSFhIVEhYmFRIWEhUTFRIWEhUSFiYVEhYSFRMVJhUTFSYVExUSAAIVThUSFhIVExUSFiYVFBQSFRIWEhUTFRIWJhUSFhIVExUmFRMVJhUTFRIAAhVOFRIWEhUTFRIWJhUSFhIVEhYSFRMVEhYmFRIWEhUSFiYVEhYmFRIWEgACFU4VEhYSFRMVEhYlFhIWEhUSFhIVExUSFiYVEhYSFRIWJhUSFiYVEhYSAAIVThUSFhIVExUSFiUWEhYSFRIWEhUTFRIWJhUSFhIVEhYmFRIWJhUSFhIAAhVOFRIWEhUSFhIWJRYSFhIVEhYSFRMVEhYlFhIWEhUSFiYVEhYmFRIWEgACFU4VEhYSFRIWEhUmFhIWEhUSFhIVEhYSFiUWEhYSFRIWJhUSFiYVEhYSAA0FAAA="
    - name: "soundbar laptop"
      command_on: "JgA0AUwVJhYSFRIWEhUmFhIVExUSFhIVEhYSFSYWEhUTFRIWJhUSFiYVEhYSAAIBThUmFRMVEhYSFSYVExUSFhIVEhYSFhIVJhYSFRIWEhUmFhIVJhYSFRIAAgJNFiUWEhYSFRMVJhUSFhIVEhYSFhIVEhYmFRIWEhUSFiYVEhYmFRIWEwACAE4VJhYSFRIWEhUmFhIVExUSFhIVEhYSFSYWEhUTFRIWJRYSFiUWEhYSAAIBThUmFRIWEhYSFSYVExUSFhIVEhYSFRMVJhUTFRIWEhUuDhIVJhYSFRIAAgJNFiYVEhYSFRIWJhUSFhIVExUSFhIVEhYmFRIWEhUTFSYVExUmFRMVEgACAk0VJhYSFRMVEhYlFhIWEhUSFhIVExUTFSUWEhYSFRIWJhUSFiYVEhYSAA0FAAA="
      command_off: "JgA0AUwVJhYSFRIWEhUmFhIVExUSFhIVEhYSFSYWEhUTFRIWJhUSFiYVEhYSAAIBThUmFRMVEhYSFSYVExUSFhIVEhYSFhIVJhYSFRIWEhUmFhIVJhYSFRIAAgJNFiUWEhYSFRMVJhUSFhIVEhYSFhIVEhYmFRIWEhUSFiYVEhYmFRIWEwACAE4VJhYSFRIWEhUmFhIVExUSFhIVEhYSFSYWEhUTFRIWJRYSFiUWEhYSAAIBThUmFRIWEhYSFSYVExUSFhIVEhYSFRMVJhUTFRIWEhUuDhIVJhYSFRIAAgJNFiYVEhYSFRIWJhUSFhIVExUSFhIVEhYmFRIWEhUTFSYVExUmFRMVEgACAk0VJhYSFRMVEhYlFhIWEhUSFhIVExUTFSUWEhYSFRIWJhUSFiYVEhYSAA0FAAA="
    - name: "soundbar tv"
      command_on: "JgDMAEwVEhYmFRIWJhUSFiYVJhUSFhIWExQSFicUJhUTFRIAArRNFhMUJhUTFSYVExUnFCYWEhUSFhIVExUmFSYWEhUTAAKzTRYSFSYWEhUnFRIVJhYmFRIWEhUSFhIVJhYmFRMVEgACs08UEhYmFRIWJhUSFiYVJhUTFRIWExQSFiYVJxUSFRIAArRNFhIVJxQTFSYVExUmFSYWEhUTFRIWEhUmFiUWEhYSAAKzThUSFiUWEhYlFhIWJRYmFRIWEhUTFRIWJhUnFBMVEgANBQAAAAAAAAAAAAA="
      command_off: "JgDMAEwVEhYmFRIWJhUSFiYVJhUSFhIWExQSFicUJhUTFRIAArRNFhMUJhUTFSYVExUnFCYWEhUSFhIVExUmFSYWEhUTAAKzTRYSFSYWEhUnFRIVJhYmFRIWEhUSFhIVJhYmFRMVEgACs08UEhYmFRIWJhUSFiYVJhUTFRIWExQSFiYVJxUSFRIAArRNFhIVJxQTFSYVExUmFSYWEhUTFRIWEhUmFiUWEhYSAAKzThUSFiUWEhYlFhIWJRYmFRIWEhUTFRIWJhUnFBMVEgANBQAAAAAAAAAAAAA="
    - name: "soundbar ok"
      command_on: "JgDuAEwVEhYSFSYWJhUSFhIVEhYSFRIWExUSFSYWJhUSFRMAAttNFhMUEhYmFSYWEhUSFhIVExUSFhIVEhYmFSYVExUSAALbThUSFhMUJhYlFhMVEhUSFhIVExUTFBMVJhUnFRIVEwAC2k4VExUSFSYWJhUSFhIVExUSFhIVEhYTFCYWJhUSFhIAAttNFhMUExUmFSYWEhUSFhMUExUTFRMUEhYnFCYWEhUSAALbThUSFhMUJxUnFBIWExQSFhIVExUSFhIVJhYmFRIWEgAC200VExUSFiUWJhUTFRIWEhUSFhIVExUSFiUWJhUSFhIADQUAAAAAAAAAAA=="
      command_off: "JgDuAEwVEhYSFSYWJhUSFhIVEhYSFRIWExUSFSYWJhUSFRMAAttNFhMUEhYmFSYWEhUSFhIVExUSFhIVEhYmFSYVExUSAALbThUSFhMUJhYlFhMVEhUSFhIVExUTFBMVJhUnFRIVEwAC2k4VExUSFSYWJhUSFhIVExUSFhIVEhYTFCYWJhUSFhIAAttNFhMUExUmFSYWEhUSFhMUExUTFRMUEhYnFCYWEhUSAALbThUSFhMUJxUnFBIWExQSFhIVExUSFhIVJhYmFRIWEgAC200VExUSFiUWJhUTFRIWEhUSFhIVExUSFiUWJhUSFhIADQUAAAAAAAAAAA=="
    - name: "tv youtube"
      command_on: "JgDMAHA7DRANLA0QDRAMEA0QDRAMEA0QDRAMEA0QDRAMLQ0QDQ8NEA0QDBANEA0QDBANEA0sDRANEA0sDRANEA0QDRAMEQwQDS0NLQwQDS0MLQ4PDS0NDw0tDRAMEA0tDC0NEA4PDQAJrHE7DRANLQwRDBAODw0QDRANEA0QDRAMEA0QDRANLQwQDg8NEAwQDg8NEAwQDRANEAwtDRANDw0tDRAMEA0QDRAMEA0QDSwNLQ0QDC0NLQwQDS0NEAwtDRANEAwtDS0MEA0QDQANBQAAAAAAAAAAAAA="
      command_off: "JgDMAHE6DRANLA4PDRAMEA0QDRAMEA0QDRAMEQwQDRAMLQ0QDRAMEQwRDBANEA0RDBANEAwtDg8NEQsQDRANEQsQDRANEQstDiwNDw4QDCwNEQ0sDSwNLQ4rDRANEA0tDRANLA0QDQAJq3I7DRAMLQ0RDBEMEQwQDBEMEQwRDBEMEQwRCxENLA4QDBANEA0PDRAMEQwQDBAOEAwtDRAMEA0QDBANEA0PDRANEQstDS0MEQ0QDC0NEA0sDiwNLA0tDREMDw0uDQ4NLQ4QDAANBQAAAAAAAAAAAAA="
    - name: "tv nextflix"
      command_on: "JgDMAHA7DRAMLQ4PDRAMEA0QDRAMEA0QDRAMEA0QDRAMLQ0QDQ8NEA0QDQ8NEA0QDQ8ODw0tDC0NEA0QDiwMEA0QDRAMEA0QDisNEA0QDC0NLQwtDS0NLA0tDRANLQwtDS0MLQ0QDQAJrHE7DRANLA0QDRAMEA0QDRAMEA0QDRAMEA0QDQ8NLQ0QDBANEA0QDBANEA0PDRANEA0sDiwNEA0PDS0NDw0QDRANDw0QDS0MEA4PDSwOLA0sDiwOKw0tDRANLA4sDSwOLA0QDQANBQAAAAAAAAAAAAA="
      command_off: "JgDMAHE6DRANLA4PDRAMEA0QDRAMEA0QDRAMEQwQDRAMLQ0QDRAMEQwRDBANEA0RDBANEAwtDg8NEQsQDRANEQsQDRANEQstDiwNDw4QDCwNEQ0sDSwNLQ4rDRANEA0tDRANLA0QDQAJq3I7DRAMLQ0RDBEMEQwQDBEMEQwRDBEMEQwRCxENLA4QDBANEA0PDRAMEQwQDBAOEAwtDRAMEA0QDBANEA0PDRANEQstDS0MEQ0QDC0NEA0sDiwNLA0tDREMDw0uDQ4NLQ4QDAANBQAAAAAAAAAAAAA="
    - name: "tv power"
      command_on: "JgAyAW88DBANLQ0PDRANEAwRDBAMEQwQDRANEAsRDRANLA0RDBAMEQwQDRELEA0QDg8MEQwtDBEMEQwQDRANEA0QDRAMEQwtDRANLA0tDSwNLQ4PDBAOLA0QDSwNLA0tDS0MEA0tDgAJq3E8DBANLQ0PDRANEAwQDRANEA4PDBANEA0PDREMLA0RDBEMEA0RCxEMEQwQDRANEA0tDBANEA0QDBANEA0RCxANEQstDRANLA4sDS0MLQ0QDRAMLQ4PDC0OLAwtDS0MEA0tDQAJrHE7DRAMLQ0QDBANEA0QDBANEA0QDBEMEA4PDBEMLQ0QDBEMEA0PDRAMEQwRDBELEA0tDg8MEQwRDQ8NEA4PDRANEQwsDg8NLA0tDSwOLA4PDBEMLQ0QDSwNLA0tDiwNDw0tDAANBQAAAAA="
      command_off: "JgAyAW88DBANLQ0PDRANEAwRDBAMEQwQDRANEAsRDRANLA0RDBAMEQwQDRELEA0QDg8MEQwtDBEMEQwQDRANEA0QDRAMEQwtDRANLA0tDSwNLQ4PDBAOLA0QDSwNLA0tDS0MEA0tDgAJq3E8DBANLQ0PDRANEAwQDRANEA4PDBANEA0PDREMLA0RDBEMEA0RCxEMEQwQDRANEA0tDBANEA0QDBANEA0RCxANEQstDRANLA4sDS0MLQ0QDRAMLQ4PDC0OLAwtDS0MEA0tDQAJrHE7DRAMLQ0QDBANEA0QDBANEA0QDBEMEA4PDBEMLQ0QDBEMEA0PDRAMEQwRDBELEA0tDg8MEQwRDQ8NEA4PDRANEQwsDg8NLA0tDSwOLA4PDBEMLQ0QDSwNLA0tDiwNDw0tDAANBQAAAAA="
    - name: "tv hdmi"
      command_on: "JgAyAW88DBANLQ0QDBEMEA0QDg8NEA0RCxANEA0RDBANLQ0PDRANEAwRDBANEAwQDRANEQstDRAMEQwQDRANDw0RDBAMEQwtDRAMLQ0QDRAMEQwRDBAOLA0QDC0NEQsRDBANEQwsDgAJrHA8DRANLA4QCxAOEAwQDBAODw4PDBANEQ0PDBANLQ0PDRAODw0PDRANEAwRDBEMEA0sDRANEAwQDRAMEA0RDBANDw0tDBEMLQ0RDA8NEA4QDA8NLQ0RCy0NEQwPDg8NEAwtDQAJrXA7DRANLQwRDBAOEAsQDREMEA0PDRANEAwRDBEMLA0QDRAMEQwQDRELEQwQDRAMEQwtDBEMEA0QDRANEQ0PDBEMEQ0sDRANLA4QDBAMEA4QDQ8MLQ0QDSwOEA0PDRAMEQwtDQANBQAAAAA="
      command_off: "JgDMAHE6DRANLA4PDRAMEA0QDRAMEA0QDRAMEQwQDRAMLQ0QDRAMEQwRDBANEA0RDBANEAwtDg8NEQsQDRANEQsQDRANEQstDiwNDw4QDCwNEQ0sDSwNLQ4rDRANEA0tDRANLA0QDQAJq3I7DRAMLQ0RDBEMEQwQDBEMEQwRDBEMEQwRCxENLA4QDBANEA0PDRAMEQwQDBAOEAwtDRAMEA0QDBANEA0PDRANEQstDS0MEQ0QDC0NEA0sDiwNLA0tDREMDw0uDQ4NLQ4QDAANBQAAAAAAAAAAAAA="
    - name: "tv mute"
      command_on: "JgDMAG88DQ8OLAwQDRANEAwQDRANEA0QDBEMEAwRDBANLQwQDRANEAwQDRAODg0RDBANEAwtDREMEA0QDBENDw0RDBENDw0QDC0NEQ0PDC0NLQ0PDREMEAwtDg8NEQ0sDC0ODwwtDQAJrXE7DhAMLQ0PDRANEA0QDBAODwwQDhANDwwRDQ8NLA0QDREMDw4PDg8NEAsRDRELEA4sDQ8NEQwQDQ8NEQwRDA8NEA4PDC0NEA0QDS0MLQ4PDRAMEA4sDBANEA0sDS0NEAwtDgANBQAAAAAAAAAAAAA="
      command_off: "JgDMAG88DQ8OLAwQDRANEAwQDRANEA0QDBEMEAwRDBANLQwQDRANEAwQDRAODg0RDBANEAwtDREMEA0QDBENDw0RDBENDw0QDC0NEQ0PDC0NLQ0PDREMEAwtDg8NEQ0sDC0ODwwtDQAJrXE7DhAMLQ0PDRANEA0QDBAODwwQDhANDwwRDQ8NLA0QDREMDw4PDg8NEAsRDRELEA4sDQ8NEQwQDQ8NEQwRDA8NEA4PDC0NEA0QDS0MLQ4PDRAMEA4sDBANEA0sDS0NEAwtDgANBQAAAAAAAAAAAAA="

- platform: template
  switches:
    alarm_on_off:
      friendly_name: "Alarm system"
      turn_on:
        service: tapo_control.set_alarm_mode
        data:
          entity_id: camera.camera_hd
          alarm_mode: 'on'
          sound: 'on'
          light: 'on'
      turn_off:
        service: tapo_control.set_alarm_mode
        data:
          entity_id: camera.camera_hd
          alarm_mode: 'off'
          sound: 'off'
          light: 'on'
    camera_on_off:
      friendly_name: "Tapo C100"
      turn_on:
        service: tapo_control.set_privacy_mode
        data:
          entity_id: camera.camera_hd
          privacy_mode: 'off'
      turn_off:
        service: tapo_control.set_privacy_mode
        data:
          entity_id: camera.camera_hd
          privacy_mode: 'on'
    game_mode_on_off:
      friendly_name: "Game mode"
      turn_on:
        service: script.game_mode_on
      turn_off:
        service: script.game_mode_off

- platform: wake_on_lan
  mac: !secret desktop_mac
  host: !secret desktop_ip
  name: Desktop
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: Desktop

- platform: wake_on_lan
  mac: !secret laptop_mac
  host: !secret laptop_ip
  name: Laptop
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: Laptop
