- platform: broadlink
  mac: !secret living_room_mac
  switches:
    - name: "Soundbar display"
      command_on: "JgDMAEsWJhUmFhIVJhYSFRIWJhUSFhIVEhYSFiUWJhUTFRIAArRNFiUWJhUTFSYVExUSFiUWEhYSFRIWExQmFiYVEhYSAAKzThUmFiYVEhYmFRIWExQmFhIVEhYSFRMVJhUmFhIVEwACs04VJhUmFhIVJhYSFRIWJhUTFRIVExUSFiYVJhUTFRIAArRNFiYVJhUTFSYVExUTFSYVExUSFRIWEhUmFiYVEhYSAAK0TRYlFiYVEhYmFRMVEhYlFhIWEhUSFhIVJhYmFRIWEgANBQAAAAAAAAAAAAA="
      command_off: "JgDMAEsWJhUmFhIVJhYSFRIWJhUSFhIVEhYSFiUWJhUTFRIAArRNFiUWJhUTFSYVExUSFiUWEhYSFRIWExQmFiYVEhYSAAKzThUmFiYVEhYmFRIWExQmFhIVEhYSFRMVJhUmFhIVEwACs04VJhUmFhIVJhYSFRIWJhUTFRIVExUSFiYVJhUTFRIAArRNFiYVJhUTFSYVExUTFSYVExUSFRIWEhUmFiYVEhYSAAK0TRYlFiYVEhYmFRMVEhYlFhIWEhUSFhIVJhYmFRIWEgANBQAAAAAAAAAAAAA="
    - name: "Soundbar vertical"
      command_on: "JgDcAEwVEhYmFScUJhYmFSYWJhUSFhIVEhYSFSYWEhUTFRMVJhUSFiYVExUSAAGyTRYSFSYWJhUmFiYVJhUmFhIVExUSFhIVJhYSFRIWEhUnFRIVJhYSFRMAAbJNFhIVJhYmFSYVJhYmFSYWExQTFRMUExUnFBMVEhYSFSYWEhUmFhIVEgABs00WEhUmFSYWJhUmFiYVJhUTFRIWEhUSFiYVExUSFRIWJhUSFiYVExUSAAGyThUSFiYVJhYmFSYVJhYnFBIWEhUTFRIWJhUSFhIVEhYmFRIWJhUSFhIADQUAAAAAAAAAAAAA"
      command_off: "JgDcAEwVEhYmFScUJhYmFSYWJhUSFhIVEhYSFSYWEhUTFRMVJhUSFiYVExUSAAGyTRYSFSYWJhUmFiYVJhUmFhIVExUSFhIVJhYSFRIWEhUnFRIVJhYSFRMAAbJNFhIVJhYmFSYVJhYmFSYWExQTFRMUExUnFBMVEhYSFSYWEhUmFhIVEgABs00WEhUmFSYWJhUmFiYVJhUTFRIWEhUSFiYVExUSFRIWJhUSFiYVExUSAAGyThUSFiYVJhYmFSYVJhYnFBIWEhUTFRIWJhUSFhIVEhYmFRIWJhUSFhIADQUAAAAAAAAAAAAA"
    - name: "Soundbar ok"
      command_on: "JgDuAEwVEhYSFSYWJhUSFhIVEhYSFRIWExUSFSYWJhUSFRMAAttNFhMUEhYmFSYWEhUSFhIVExUSFhIVEhYmFSYVExUSAALbThUSFhMUJhYlFhMVEhUSFhIVExUTFBMVJhUnFRIVEwAC2k4VExUSFSYWJhUSFhIVExUSFhIVEhYTFCYWJhUSFhIAAttNFhMUExUmFSYWEhUSFhMUExUTFRMUEhYnFCYWEhUSAALbThUSFhMUJxUnFBIWExQSFhIVExUSFhIVJhYmFRIWEgAC200VExUSFiUWJhUTFRIWEhUSFhIVExUSFiUWJhUSFhIADQUAAAAAAAAAAA=="
      command_off: "JgDuAEwVEhYSFSYWJhUSFhIVEhYSFRIWExUSFSYWJhUSFRMAAttNFhMUEhYmFSYWEhUSFhIVExUSFhIVEhYmFSYVExUSAALbThUSFhMUJhYlFhMVEhUSFhIVExUTFBMVJhUnFRIVEwAC2k4VExUSFSYWJhUSFhIVExUSFhIVEhYTFCYWJhUSFhIAAttNFhMUExUmFSYWEhUSFhMUExUTFRMUEhYnFCYWEhUSAALbThUSFhMUJxUnFBIWExQSFhIVExUSFhIVJhYmFRIWEgAC200VExUSFiUWJhUTFRIWEhUSFhIVExUSFiUWJhUSFhIADQUAAAAAAAAAAA=="
    - name: "Teco power"
      command_on: "JgDQACgPKg8NKioPKg8NKg4pDSoNKQ4pDikqAAUcKg8qDw0qKg8rDw0qDSoNKQ4pDikNKSsABRwqDyoPDSoqDysPDCsNKg0pDikNKg0pKwAFHCoPKg8NKioQKg8NKg4pDSoNKQ4pDikqAAUcKg8rDwwrKg8qEAwrDSkOKQ4pDSoNKSoABR0qDyoPDSoqECoPDSoOKQ0qDSkOKQ4pKgAFHSoPKg8NKioPKw8MKw0qDSkOKQ0qDSoqAAUcKg8qEAwqKw8qDw0qDikNKg0qDSkOKSoADQUAAAAAAAA="
      command_off: "JgDQACgPKg8NKioPKg8NKg4pDSoNKQ4pDikqAAUcKg8qDw0qKg8rDw0qDSoNKQ4pDikNKSsABRwqDyoPDSoqDysPDCsNKg0pDikNKg0pKwAFHCoPKg8NKioQKg8NKg4pDSoNKQ4pDikqAAUcKg8rDwwrKg8qEAwrDSkOKQ4pDSoNKSoABR0qDyoPDSoqECoPDSoOKQ0qDSkOKQ4pKgAFHSoPKg8NKioPKw8MKw0qDSkOKQ0qDSoqAAUcKg8qEAwqKw8qDw0qDikNKg0qDSkOKSoADQUAAAAAAAA="
    - name: "Teco volume up"
      command_on: "JgCCACcQKg8MKioQKg8NKg0qDSkOKSoPDSoNAAU2Kg8qDwwrKg8rDg0qDikNKg0pKg8NKg4ABTYpDyoQDCoqECoPDSoNKg0pDSoqDw0qDQAFNioPKg8NKioPKw8MKw0pDikNKioPDCsNAAU2Kg8qDw0qKg8qDw0qDikNKg0pKg8NKg4ADQUAAAAA"
      command_off: "JgCCACcQKg8MKioQKg8NKg0qDSkOKSoPDSoNAAU2Kg8qDwwrKg8rDg0qDikNKg0pKg8NKg4ABTYpDyoQDCoqECoPDSoNKg0pDSoqDw0qDQAFNioPKg8NKioPKw8MKw0pDikNKioPDCsNAAU2Kg8qDw0qKg8qDw0qDikNKg0pKg8NKg4ADQUAAAAA"
    - name: "Teco volume down"
      command_on: "JgBoACgPLA0NKiwNLA4sDQ0qDSoMKg0qLA0tAAUaKQ8rDwwrKg8qDysPDSoNKgwqDSoqDysABRwqDyoPDSoqDysPKhAMKwwqDSoNKioPKgAFHSkPKw8NKioPKhAqDw0qDSoMKwwqKg8rAA0FAAAAAAAAAAAAAAAAAAA="
      command_off: "JgBoACgPLA0NKiwNLA4sDQ0qDSoMKg0qLA0tAAUaKQ8rDwwrKg8qDysPDSoNKgwqDSoqDysABRwqDyoPDSoqDysPKhAMKwwqDSoNKioPKgAFHSkPKw8NKioPKhAqDw0qDSoMKwwqKg8rAA0FAAAAAAAAAAAAAAAAAAA="
    - name: "Teco timer"
      command_on: "JgCCACcQKg8MKioQKg8NKg0qDSkOKSoPDSoNAAU2Kg8qDwwrKg8rDg0qDikNKg0pKg8NKg4ABTYpDyoQDCoqECoPDSoNKg0pDSoqDw0qDQAFNioPKg8NKioPKw8MKw0pDikNKioPDCsNAAU2Kg8qDw0qKg8qDw0qDikNKg0pKg8NKg4ADQUAAAAA"
      command_off: "JgBoACgPLA0NKiwNLA4sDQ0qDSoMKg0qLA0tAAUaKQ8rDwwrKg8qDysPDSoNKgwqDSoqDysABRwqDyoPDSoqDysPKhAMKwwqDSoNKioPKgAFHSkPKw8NKioPKhAqDw0qDSoMKwwqKg8rAA0FAAAAAAAAAAAAAAAAAAA="
    - name: "National power"
      command_on: "JgAUAXB1HB0dVhweHFccHRweG1gcHR0dHFccHRxXHR0bHhxXHR0bHh1WHR0bHxseHB4cHRsfHB0bWBweHB0cHhwdHB4cIHJ1HB0dVhweHFccHR0dG1gcHRsfHFccHR1WHR0cHR1WHR0cHR1WHR0bHhweHB0cHhwdHR0bWBwdHR0cHRweHB0cIXJ1HQACDnJ1HB0dHRxXHB0dHRwdHB4cHRweHB0dVh4cHB0dHRwdHR0cHR1WHVYdHRxXHFccHR0dHB0cVxxYHB0bWBxXHB0dIHJ1HB0cHhxXHB0cHhwdGx8cHRweHB0cVxweHB0dHRwdGx8cHRxXHFcdHRxXHFceGxweHB0dVh1WHB4cVxxXHB0cIXJ1HQANBQ=="
      command_off: "JgAUAXB1HB0dVhweHFccHRweG1gcHR0dHFccHRxXHR0bHhxXHR0bHh1WHR0bHxseHB4cHRsfHB0bWBweHB0cHhwdHB4cIHJ1HB0dVhweHFccHR0dG1gcHRsfHFccHR1WHR0cHR1WHR0cHR1WHR0bHhweHB0cHhwdHR0bWBwdHR0cHRweHB0cIXJ1HQACDnJ1HB0dHRxXHB0dHRwdHB4cHRweHB0dVh4cHB0dHRwdHR0cHR1WHVYdHRxXHFccHR0dHB0cVxxYHB0bWBxXHB0dIHJ1HB0cHhxXHB0cHhwdGx8cHRweHB0cVxweHB0dHRwdGx8cHRxXHFcdHRxXHFceGxweHB0dVh1WHB4cVxxXHB0cIXJ1HQANBQ=="
    - name: "National volume up"
      command_on: "JgAUAXF1G1ccHRxXHVYcHhwdHVYcHhxXHB0dVhxXHR0cHR1WHR0bHhxYHB0cVxweGx4cHhwdHB4cVxwdHFccHhwdHB4cIHJ1HFccHR1WHFcdHRwdHVYdHRxXHB0dVh1WHB4bHhxXHhwdHBxXHhwcVx0cHB4bHhweHB0cVx4cHFcbHh4cHR0dH3F2HQACDXN0HB0cHhxXHB0cHhwdHR0cHRweHB0dVh0dHB0dHRwdHB4cHR1WHVYdHRxXHFccHhseHB4cVxxXGx4cVxxXHB4cIHJ1Gx4dHRxXHB0cHhwfGh4cHRweGx4cVxweHB0cHhwdGx8bHhxXHFccHhxXHFcbHh0dHB0cVxxXHB4bWBxXHB4cIHF2HAANBQ=="
      command_off: "JgAUAXF1G1ccHRxXHVYcHhwdHVYcHhxXHB0dVhxXHR0cHR1WHR0bHhxYHB0cVxweGx4cHhwdHB4cVxwdHFccHhwdHB4cIHJ1HFccHR1WHFcdHRwdHVYdHRxXHB0dVh1WHB4bHhxXHhwdHBxXHhwcVx0cHB4bHhweHB0cVx4cHFcbHh4cHR0dH3F2HQACDXN0HB0cHhxXHB0cHhwdHR0cHRweHB0dVh0dHB0dHRwdHB4cHR1WHVYdHRxXHFccHhseHB4cVxxXGx4cVxxXHB4cIHJ1Gx4dHRxXHB0cHhwfGh4cHRweGx4cVxweHB0cHhwdGx8bHhxXHFccHhxXHFcbHh0dHB0cVxxXHB4bWBxXHB4cIHF2HAANBQ=="
    - name: "National volume down"
      command_on: "JgAUAW91HB4dHR1WG1gbHh0dHVYdHB0dHRwbWB5VHB4dHB5VHhwdHBtYHhwcVx0cHhwdHB4cHRweVR4cHVYdHB4cHRweH3RzHhwdHBtYHlUcHh0cHlUeHB0cHhwdVh1WHRweHBtYHRweHB1WHRwdVh0dHB0dHRwdHR0cVxwdHVYdHRwdHR0bIXN0HAACD3N0HB4cHRxXHR0cHR0dHB0cHhseHB4cVxwdHB4cHR0dHB0cHhxXHFccHRxXHFcdHRwdHR0bWB1WHB0dVh1WHR0cIHN0HB4cHR1WHB4bHhweHB0dHRwdHR0bWBwdHR0cHRweHB0eHBxXG1gdHB5VHlUeHBsfHRwdVh1WHB0eVRxXHB4bIXN0HAANBQ=="
      command_off: "JgAUAW91HB4dHR1WG1gbHh0dHVYdHB0dHRwbWB5VHB4dHB5VHhwdHBtYHhwcVx0cHhwdHB4cHRweVR4cHVYdHB4cHRweH3RzHhwdHBtYHlUcHh0cHlUeHB0cHhwdVh1WHRweHBtYHRweHB1WHRwdVh0dHB0dHRwdHR0cVxwdHVYdHRwdHR0bIXN0HAACD3N0HB4cHRxXHR0cHR0dHB0cHhseHB4cVxwdHB4cHR0dHB0cHhxXHFccHRxXHFcdHRwdHR0bWB1WHB0dVh1WHR0cIHN0HB4cHR1WHB4bHhweHB0dHRwdHR0bWBwdHR0cHRweHB0eHBxXG1gdHB5VHlUeHBsfHRwdVh1WHB0eVRxXHB4bIXN0HAANBQ=="
    - name: "Mod power"
      command_on: "JgBYAAABJJQTExE5ETkRORI4EjgSExI5ERQRORE5ETkSOBI4EhMSOREUERQRFBEUEjgSOBI4EhQRORE5ETkRORITEhMSExI4EgAEgwABJUsUAAxUAAEmSxEADQU="
      command_off: "JgBYAAABJJQTExE5ETkRORI4EjgSExI5ERQRORE5ETkSOBI4EhMSOREUERQRFBEUEjgSOBI4EhQRORE5ETkRORITEhMSExI4EgAEgwABJUsUAAxUAAEmSxEADQU="
    - name: "Mod channel"
      command_on: "JgBQAAABJJUSExE5ETkSOBI4EjgSExI5ERQRORE5ETkSOBI4EhMSOBIUERQROREUETkRORITEhMSOBU2ERQROREUERQRORI4EgAEgwABJUsRAA0F"
      command_off: "JgBQAAABJpMTEhM3FDYUNhQ3FTUTEhM3ExITNxM3FDYUNhQ3ExITNxM3FBETNxQRFTUUNhQSExITEhM3ExITNxQRFBEUNhQ3EwAEgQABKEgUAA0F"
    - name: "Mod menu"
      command_on: "JgBQAAABJJQSExI5ETkRORE5EjgSExI4EhMSORE5ETkRORE5EhMSOBI4EjkROREUETkRORE5EhMSExITEhQROREUERQRFBE5EgAEggABJksRAA0F"
      command_off: "JgBQAAABJJQSExI5ETkRORE5EjgSExI4EhMSORE5ETkRORE5EhMSOBI4EjkROREUETkRORE5EhMSExITEhQROREUERQRFBE5EgAEggABJksRAA0F"
    - name: "Mod tv"
      command_on: "JgBQAAABI5UTEhI4EjkRORE5ETkSExI4EhQROBI5ETkRORE5EhMSOBI4EjkRORE5ERQRORITEhMSExITEhMSFBE5ERQRORE5EgAEgwABJUsRAA0F"
      command_off: "JgBQAAABI5UTEhI4EjkRORE5ETkSExI4EhQROBI5ETkRORE5EhMSOBI4EjkRORE5ERQRORITEhMSExITEhMSFBE5ERQRORE5EgAEgwABJUsRAA0F"

- platform: broadlink
  mac: !secret bedroom_mac
  switches:
    - name: "Gree power"
      command_on: "JgBqAScOKQ4OKSkOKQ4OKQ4qDSoOKQ4qDSop5ikOKQ4OKSkOKQ4OKg0qDikOKg0qDikp6CkOKQ4NKikOKQ4OKQ4qDSoOKQ4qDSop5ykOKQ4OKSkOKQ4OKg0qDikOKg0qDikp5ykOKQ4OKSkOKQ8NKQ4qDSoOKQ4qDikp5ykOKQ4OKSkOKQ4OKg0qDikOKg0qDikp6CkOKQ4OKSkOKQ4OKg0qDikOKg0qDikp6CkOKQ4NKikOKQ4OKQ4qDSoOKQ4qDSop5yoNKQ4OKSkOKQ4OKg0qDikOKg0qDikp5ykOKQ4OKSkOKQ8NKg4pDioNKg4pDiop6CkOKQ4NKikOKQ4OKQ4qDSoOKQ4qDSop5yoNKQ4OKSkPKA8NKg4pDioOKQ4qDSop5ykOKQ4NKikOKQ4OKQ4qDikOKg0qDikp5ykOKQ4OKSkOKQ4OKg0qDioNKg4pDiop5yoNKQ4OKSkPKA8NKg4pDioOKQ4qDSopAA0FAAAAAAAAAAAAAAAA"
      command_off: "JgBqAScOKQ4OKSkOKQ4OKQ4qDSoOKQ4qDSop5ikOKQ4OKSkOKQ4OKg0qDikOKg0qDikp6CkOKQ4NKikOKQ4OKQ4qDSoOKQ4qDSop5ykOKQ4OKSkOKQ4OKg0qDikOKg0qDikp5ykOKQ4OKSkOKQ8NKQ4qDSoOKQ4qDikp5ykOKQ4OKSkOKQ4OKg0qDikOKg0qDikp6CkOKQ4OKSkOKQ4OKg0qDikOKg0qDikp6CkOKQ4NKikOKQ4OKQ4qDSoOKQ4qDSop5yoNKQ4OKSkOKQ4OKg0qDikOKg0qDikp5ykOKQ4OKSkOKQ8NKg4pDioNKg4pDiop6CkOKQ4NKikOKQ4OKQ4qDSoOKQ4qDSop5yoNKQ4OKSkPKA8NKg4pDioOKQ4qDSop5ykOKQ4NKikOKQ4OKQ4qDikOKg0qDikp5ykOKQ4OKSkOKQ4OKg0qDioNKg4pDiop5yoNKQ4OKSkPKA8NKg4pDioOKQ4qDSopAA0FAAAAAAAAAAAAAAAA"
    - name: "Gree spin"
      command_on: "JgA4AScOKQ4NKikOKQ4OKQ4pKQ8NKg4pDioNAAECKQ4pDg0qKQ4pDg4pDikpDw0qDikOKg0AAQMpDikODikpDikODikOKikODikOKg0qDgABAikOKQ4NKikOKQ4OKQ4qKQ4OKQ4qDSoOAAECKQ4pDg0qKQ4pDg4pDikqDg0qDikOKg0AAQMpDSkODikpDikPDSoOKSkPDSoOKQ4qDQABAykOKQ4OKSkOKQ4OKg0qKQ4OKQ4qDikOAAECKg0pDg4pKQ4pDw0qDikpDw0qDikOKg0AAQMpDikODSopDikODikOKikODikOKg0qDgABAikOKQ4NKikOKQ4OKQ4pKg4NKg4pDioOAAECKQ4pDg4pKQ4pDw0qDikpDw0qDikOKg0AAQQpDikODSopDikODikOKikODikOKg0qDgANBQAAAAAAAAAAAAAAAAAA"
      command_off: "JgA4AScOKQ4NKikOKQ4OKQ4pKQ8NKg4pDioNAAECKQ4pDg0qKQ4pDg4pDikpDw0qDikOKg0AAQMpDikODikpDikODikOKikODikOKg0qDgABAikOKQ4NKikOKQ4OKQ4qKQ4OKQ4qDSoOAAECKQ4pDg0qKQ4pDg4pDikqDg0qDikOKg0AAQMpDSkODikpDikPDSoOKSkPDSoOKQ4qDQABAykOKQ4OKSkOKQ4OKg0qKQ4OKQ4qDikOAAECKg0pDg4pKQ4pDw0qDikpDw0qDikOKg0AAQMpDikODSopDikODikOKikODikOKg0qDgABAikOKQ4NKikOKQ4OKQ4pKg4NKg4pDioOAAECKQ4pDg4pKQ4pDw0qDikpDw0qDikOKg0AAQQpDikODSopDikODikOKikODikOKg0qDgANBQAAAAAAAAAAAAAAAAAA"  
    - name: "Gree speed"
      command_on: "JgDiASgOKA4OKSkOKQ4pDw0qDikOKg0qKQ4p5ykOKQ4NKikOKQ4pDg4pDioNKw0pKQ8p6CkOKA4OKSkOKQ8pDg4pDioNKg4pKQ4p6CkOKQ4OKSkOKQ4pDg4qDSoOKQ4qKQ4p5ykOKQ4OKSkOKQ4pDw0qDikOKg4pKQ4p5yoNKQ4OKSkPKA8pDg4pDioNKg4qKQ4p6CkOKQ4NKikOKQ4pDw0qDikOKg0qKQ4p6CkOKQ4OKSkOKQ4pDw0qDioNKg4pKQ8p5ykOKQ4OKSkOKQ4pDw0qDioNKg4pKQ8p5ykOKQ4OKSkOKQ8pDg0qDioNKg4pKQ8p6CkOKQ4OKSkOKQ8pDg4pDioNKg4pKg4p6CkOKQ4NKikOKQ4pDw0qDikOKg4pKQ8p5ykOKQ4OKSkOKQ8pDg4pDioOKQ4qKQ4p5yoOKQ4NKikOKQ4pDg4qDikOKg0qKQ4p6SkOKQ4NKikOKQ4pDw0qDioNKg4pKQ8p6CkOKQ4NKikOKQ4pDw0qDikOKg4pKQ8p5ykOKQ4OKSkPKQ4pDg4qDSoOKQ4qKQ4p6CkOKQ4NKikOKQ4pDw0qDikOKg4pKQ8p6CkOKQ4OKSkOKQ8pDg4pDioNKg4qKQ4p6CkOKQ4OKSkOKQ8pDg4pDioOKQ4qKQ4pAA0FAAAAAA=="
      command_off: "JgBsAScOKQ4NKikOKQ4pDg4pDioNKikOKQ4OAAEDKQ4pDg0qKQ4pDikODikOKg0qKQ4pDg4AAQQpDikODSopDikOKQ4OKQ4qDSopDikODgABAykOKQ4OKSkOKQ8oDw0qDikOKikOKQ4OAAEDKQ4pDg4pKQ4pDygPDSoOKQ4qKQ4pDg4AAQMpDikODSopDikOKRIKKg0qDikpDykODgABAykOKQ4OKSkOKQ8oDw4pDioNKikOKQ4OAAEDKg4oDg4pKg4pDikODikOKg4pKQ4pDw0AAQQpDikODSopDikOKQ8NKg4pDiopDikODgABAykOKQ4OKSkOKQ4pDw0qDikOKikOKQ4OAAEEKQ4pDg4pKQ4pDikPDSoOKQ4qKQ4pDg4AAQQpDikODSopDikOKQ4OKg0qDikpDykODgABAykOKQ4OKSkOKQ4pDw0qDioNKikOKQ8NAAEDKQ4pDg4pKQ4qDikODikOKg4pKQ4pDw0ADQUAAAAAAAAAAAAA"

- platform: template
  switches:
    alarm_on_off:
      friendly_name: "Alarm mode"
      turn_on:
        service: tapo_control.set_alarm_mode
        data:
          entity_id: camera.camera_hd
          alarm_mode: 'on'
          sound: 'on'
          light: 'on'
      turn_off:
        service: tapo_control.set_alarm_mode
        data:
          entity_id: camera.camera_hd
          alarm_mode: 'off'
          sound: 'off'
          light: 'on'
    camera_on_off:
      friendly_name: "Camera mode"
      turn_on:
        service: tapo_control.set_privacy_mode
        data:
          entity_id: camera.camera_hd
          privacy_mode: 'off'
      turn_off:
        service: tapo_control.set_privacy_mode
        data:
          entity_id: camera.camera_hd
          privacy_mode: 'on'
    game_mode_on_off:
      friendly_name: "Game mode"
      turn_on:
        service: script.game_mode_on
      turn_off:
        service: script.game_mode_off
    movie_mode_on_off:
      friendly_name: "Movie mode"
      turn_on:
        service: script.movie_mode_on
      turn_off:
        service: script.movie_mode_off

- platform: wake_on_lan
  mac: !secret desktop_mac
  host: !secret desktop_ip
  name: Desktop
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: Desktop

- platform: wake_on_lan
  mac: !secret acer_mac
  host: !secret acer_ip
  name: Acer
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: Acer

- platform: wake_on_lan
  mac: !secret huawei_mac
  host: !secret huawei_ip
  name: Huawei
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: Huawei
